export type GroupTheme = {
  primary: string
  secondary: string
  gradient: string
  cardGradient: string
  world: string
  worldKo: string
  emoji: string
  textColor: string
  borderColor: string
  bgColor: string
  glowColor: string
}

export const GROUP_THEMES: Record<string, GroupTheme> = {
  BTS: {
    primary: '#7B2D8B',
    secondary: '#3A0D5C',
    gradient: 'linear-gradient(135deg, #7B2D8B, #3A0D5C)',
    cardGradient: 'from-[#7B2D8B] to-[#1a0030]',
    world: 'Purple Planet',
    worldKo: '퍼플 플래닛',
    emoji: '💜',
    textColor: 'text-purple-300',
    borderColor: 'border-purple-500',
    bgColor: 'bg-purple-500/10',
    glowColor: 'shadow-purple-500/30',
  },
  블랙핑크: {
    primary: '#FF0090',
    secondary: '#000000',
    gradient: 'linear-gradient(135deg, #FF0090, #000000)',
    cardGradient: 'from-[#FF0090] to-[#1a0010]',
    world: 'Pink Kingdom',
    worldKo: '핑크 킹덤',
    emoji: '🖤',
    textColor: 'text-pink-400',
    borderColor: 'border-pink-500',
    bgColor: 'bg-pink-500/10',
    glowColor: 'shadow-pink-500/30',
  },
  에스파: {
    primary: '#8B5CF6',
    secondary: '#5BC8F5',
    gradient: 'linear-gradient(135deg, #8B5CF6, #5BC8F5)',
    cardGradient: 'from-[#8B5CF6] to-[#5BC8F5]',
    world: 'Silver Matrix',
    worldKo: '실버 매트릭스',
    emoji: '🤖',
    textColor: 'text-violet-300',
    borderColor: 'border-violet-400',
    bgColor: 'bg-violet-400/10',
    glowColor: 'shadow-violet-400/30',
  },
  뉴진스: {
    primary: '#FFFFFF',
    secondary: '#5BC8F5',
    gradient: 'linear-gradient(135deg, #FFFFFF, #5BC8F5)',
    cardGradient: 'from-white to-[#5BC8F5]',
    world: 'Blue Dream',
    worldKo: '블루 드림',
    emoji: '🐰',
    textColor: 'text-sky-200',
    borderColor: 'border-sky-300',
    bgColor: 'bg-sky-300/10',
    glowColor: 'shadow-sky-300/20',
  },
  세븐틴: {
    primary: '#F7CAC9',
    secondary: '#91A8D0',
    gradient: 'linear-gradient(135deg, #F7CAC9, #91A8D0)',
    cardGradient: 'from-[#F7CAC9] to-[#91A8D0]',
    world: 'Crystal Star',
    worldKo: '크리스탈 스타',
    emoji: '💎',
    textColor: 'text-rose-200',
    borderColor: 'border-rose-300',
    bgColor: 'bg-rose-300/10',
    glowColor: 'shadow-rose-300/20',
  },
  스트레이키즈: {
    primary: '#FF0000',
    secondary: '#000000',
    gradient: 'linear-gradient(135deg, #FF0000, #000000)',
    cardGradient: 'from-[#FF0000] to-[#1a0000]',
    world: 'Dark Zone',
    worldKo: '다크 존',
    emoji: '🐺',
    textColor: 'text-red-400',
    borderColor: 'border-red-500',
    bgColor: 'bg-red-500/10',
    glowColor: 'shadow-red-500/30',
  },
  트와이스: {
    primary: '#FF2D78',
    secondary: '#FBCEB1',
    gradient: 'linear-gradient(135deg, #FF2D78, #FBCEB1)',
    cardGradient: 'from-[#FF2D78] to-[#FBCEB1]',
    world: 'Neon Garden',
    worldKo: '네온 가든',
    emoji: '🌸',
    textColor: 'text-pink-400',
    borderColor: 'border-pink-400',
    bgColor: 'bg-pink-400/10',
    glowColor: 'shadow-pink-400/30',
  },
  'NCT 127': {
    primary: '#A8C87A',
    secondary: '#2E5020',
    gradient: 'linear-gradient(135deg, #A8C87A, #2E5020)',
    cardGradient: 'from-[#A8C87A] to-[#1a3010]',
    world: 'Neo City',
    worldKo: '네오 시티',
    emoji: '💚',
    textColor: 'text-lime-300',
    borderColor: 'border-lime-400',
    bgColor: 'bg-lime-400/10',
    glowColor: 'shadow-lime-400/30',
  },
  아이브: {
    primary: '#FFFFFF',
    secondary: '#B0B8C8',
    gradient: 'linear-gradient(135deg, #FFFFFF, #B0B8C8)',
    cardGradient: 'from-white to-[#B0B8C8]',
    world: 'Pearl World',
    worldKo: '펄 월드',
    emoji: '🤍',
    textColor: 'text-white',
    borderColor: 'border-white/50',
    bgColor: 'bg-white/10',
    glowColor: 'shadow-white/20',
  },
  르세라핌: {
    primary: '#81A5F9',
    secondary: '#1A3A8F',
    gradient: 'linear-gradient(135deg, #81A5F9, #1A3A8F)',
    cardGradient: 'from-[#81A5F9] to-[#0f2260]',
    world: 'Fearless Blue',
    worldKo: '피어리스 블루',
    emoji: '🔵',
    textColor: 'text-blue-300',
    borderColor: 'border-blue-400',
    bgColor: 'bg-blue-400/10',
    glowColor: 'shadow-blue-400/30',
  },
  에이티즈: {
    primary: '#C9A96E',
    secondary: '#0D0A03',
    gradient: 'linear-gradient(135deg, #C9A96E, #0D0A03)',
    cardGradient: 'from-[#C9A96E] to-[#0D0A03]',
    world: 'Treasure Island',
    worldKo: '트레저 아일랜드',
    emoji: '⚓',
    textColor: 'text-yellow-300',
    borderColor: 'border-yellow-500',
    bgColor: 'bg-yellow-500/10',
    glowColor: 'shadow-yellow-500/30',
  },
  투모로우바이투게더: {
    primary: '#6ECFF5',
    secondary: '#70E8C8',
    gradient: 'linear-gradient(135deg, #6ECFF5, #70E8C8)',
    cardGradient: 'from-[#6ECFF5] to-[#70E8C8]',
    world: 'Chaos Garden',
    worldKo: '카오스 가든',
    emoji: '🌀',
    textColor: 'text-cyan-300',
    borderColor: 'border-cyan-400',
    bgColor: 'bg-cyan-400/10',
    glowColor: 'shadow-cyan-400/30',
  },
  엔하이픈: {
    primary: '#FF8C00',
    secondary: '#7B3300',
    gradient: 'linear-gradient(135deg, #FF8C00, #7B3300)',
    cardGradient: 'from-[#FF8C00] to-[#3A1500]',
    world: 'Dark Blood',
    worldKo: '다크 블러드',
    emoji: '🦋',
    textColor: 'text-orange-300',
    borderColor: 'border-orange-400',
    bgColor: 'bg-orange-400/10',
    glowColor: 'shadow-orange-400/30',
  },
  라이즈: {
    primary: '#FF6600',
    secondary: '#8B3000',
    gradient: 'linear-gradient(135deg, #FF6600, #8B3000)',
    cardGradient: 'from-[#FF6600] to-[#3A1000]',
    world: 'Rise City',
    worldKo: '라이즈 시티',
    emoji: '🌅',
    textColor: 'text-orange-400',
    borderColor: 'border-orange-500',
    bgColor: 'bg-orange-500/10',
    glowColor: 'shadow-orange-500/30',
  },
  제로베이스원: {
    primary: '#74B9FF',
    secondary: '#0044AA',
    gradient: 'linear-gradient(135deg, #74B9FF, #0044AA)',
    cardGradient: 'from-[#74B9FF] to-[#0044AA]',
    world: 'Zero Base',
    worldKo: '제로 베이스',
    emoji: '⭐',
    textColor: 'text-sky-300',
    borderColor: 'border-sky-400',
    bgColor: 'bg-sky-400/10',
    glowColor: 'shadow-sky-400/30',
  },
  코르티스: {
    primary: '#FF2D2D',
    secondary: '#6B0000',
    gradient: 'linear-gradient(135deg, #FF2D2D, #6B0000)',
    cardGradient: 'from-[#FF2D2D] to-[#6B0000]',
    world: 'TNT Zone',
    worldKo: 'TNT 존',
    emoji: '💥',
    textColor: 'text-red-400',
    borderColor: 'border-red-500',
    bgColor: 'bg-red-500/10',
    glowColor: 'shadow-red-500/30',
  },
  베이비몬스터: {
    primary: '#FF2D9D',
    secondary: '#0055FF',
    gradient: 'linear-gradient(135deg, #FF2D9D, #0055FF)',
    cardGradient: 'from-[#FF2D9D] to-[#0055FF]',
    world: 'Monster World',
    worldKo: '몬스터 월드',
    emoji: '👾',
    textColor: 'text-pink-300',
    borderColor: 'border-pink-400',
    bgColor: 'bg-pink-400/10',
    glowColor: 'shadow-pink-400/30',
  },
  아일릿: {
    primary: '#FF85C0',
    secondary: '#9B6DD5',
    gradient: 'linear-gradient(135deg, #FF85C0, #9B6DD5)',
    cardGradient: 'from-[#FF85C0] to-[#9B6DD5]',
    world: 'Magnetic Field',
    worldKo: '마그네틱 필드',
    emoji: '🌷',
    textColor: 'text-pink-300',
    borderColor: 'border-pink-400',
    bgColor: 'bg-pink-400/10',
    glowColor: 'shadow-pink-400/30',
  },
  여자아이들: {
    primary: '#E11900',
    secondary: '#7E00BF',
    gradient: 'linear-gradient(135deg, #E11900, #7E00BF)',
    cardGradient: 'from-[#E11900] to-[#7E00BF]',
    world: 'Queendom',
    worldKo: '퀸덤',
    emoji: '👑',
    textColor: 'text-red-400',
    borderColor: 'border-red-500',
    bgColor: 'bg-red-500/10',
    glowColor: 'shadow-red-500/30',
  },
  있지: {
    primary: '#FFFFFF',
    secondary: '#9B59B6',
    gradient: 'linear-gradient(135deg, #FFFFFF, #9B59B6)',
    cardGradient: 'from-white to-[#9B59B6]',
    world: 'Crazy Land',
    worldKo: '크레이지 랜드',
    emoji: '⚡',
    textColor: 'text-purple-300',
    borderColor: 'border-purple-400',
    bgColor: 'bg-purple-400/10',
    glowColor: 'shadow-purple-400/20',
  },
  레드벨벳: {
    primary: '#F4726B',
    secondary: '#C13B5A',
    gradient: 'linear-gradient(135deg, #F4726B, #C13B5A)',
    cardGradient: 'from-[#F4726B] to-[#6B0030]',
    world: 'Velvet Room',
    worldKo: '벨벳 룸',
    emoji: '🌹',
    textColor: 'text-rose-300',
    borderColor: 'border-rose-400',
    bgColor: 'bg-rose-400/10',
    glowColor: 'shadow-rose-400/30',
  },
}

const GROUP_NAME_EN: Record<string, string> = {
  BTS: 'BTS',
  블랙핑크: 'BLACKPINK',
  에스파: 'aespa',
  뉴진스: 'NewJeans',
  세븐틴: 'SEVENTEEN',
  스트레이키즈: 'Stray Kids',
  트와이스: 'TWICE',
  'NCT 127': 'NCT 127',
  아이브: 'IVE',
  르세라핌: 'LE SSERAFIM',
  에이티즈: 'ATEEZ',
  투모로우바이투게더: 'TXT',
  엔하이픈: 'ENHYPEN',
  라이즈: 'RIIZE',
  제로베이스원: 'ZEROBASEONE',
  코르티스: 'KORTIS',
  베이비몬스터: 'BABYMONSTER',
  아일릿: 'ILLIT',
  여자아이들: '(G)I-DLE',
  있지: 'ITZY',
  레드벨벳: 'Red Velvet',
}

export function groupDisplayName(name: string, locale: string): string {
  return locale === 'ko' ? name : (GROUP_NAME_EN[name] ?? name)
}

export function worldName(theme: GroupTheme, locale: string): string {
  return locale === 'ko' ? theme.worldKo : theme.world
}

export function getTheme(groupName: string): GroupTheme {
  return GROUP_THEMES[groupName] ?? {
    primary: '#EC4899',
    secondary: '#7C3AED',
    gradient: 'linear-gradient(135deg, #EC4899, #7C3AED)',
    cardGradient: 'from-pink-500 to-purple-700',
    world: 'Kversee',
    worldKo: '케이버스',
    emoji: '🎤',
    textColor: 'text-pink-400',
    borderColor: 'border-pink-500',
    bgColor: 'bg-pink-500/10',
    glowColor: 'shadow-pink-500/30',
  }
}
